/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Karthick' at '2/22/17 1:21 AM' with Gradle 2.14.1
 *
 * @author Karthick, @date 2/22/17 1:21 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
